version: "3.3"

services: 
  app: 
    build: 
      dockerfile: ./Dockerfile-dev
      context: .
    ports: 
      - "8080:8080"
    volumes: 
      - ./:/go/src/github.com/psmarcin/youtubeGoesPodcast/
