# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2



jobs:
  tests: 
    docker:
      - image: circleci/golang:1.11-node
    working_directory: /go/src/github.com/psmarcin/youtubeGoesPodcast
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v ./...
  build:
    filters:
      branches:
        only:
          - master
    docker:
      # specify the version
      - image: circleci/golang:1.11-node
    working_directory: /go/src/github.com/psmarcin/youtubeGoesPodcast
    steps:
      - checkout
      - run: sudo yarn global add now
      - run: ./deploy-ci.sh
